version: "3"

services:
  bbav_code:
    image: bbav:latest
    container_name: "bbav_code"
    # command: bash -c "cd BBAVectors-Oriented-Object-Detection/datasets/DOTA_devkit &&
    #          python dota_evaluation_task1.py"
    command: bash -c "cd src &&
             python main.py --data_dir /BBAV/DS/train --num_epoch 5 --batch_size 4 --dataset dota --phase train --classnames ./configs/classes.txt"
    volumes:
      - PATH_TO_DATASET:/BBAV/DS
      - PATH_TO_SAVE_DIR:/BBAV/models/
      - ./src:/BBAV/src
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
